os: linux
dist: xenial
cache: pip
language: python
python:
  - "3.8"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -q -r requirements.txt
  - conda install -c conda-forge rdkit
  - pip install biopython
  - conda install -c conda-forge mdtraj
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - |
    set -e
    for n in */*.ipynb
    do
      jupyter nbconvert --to notebook --execute $n
    done
env:
  - GEOMSTATS_BACKEND=numpy
