os: linux
dist: xenial
cache: pip
language: python
python:
  - "3.8"

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -q -r requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -c conda-forge -n ppi_tda rdkit
  - conda activate ppi_tda
  - pip install frozendict
  - pip install scikit-learn==0.23.2
  - pip install giotto-tda
  - pip install biopython
  - conda install -c conda-forge mdtraj
before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
script:
  - |
    set -e
    for n in */*.ipynb
    do
      jupyter nbconvert --to notebook --execute $n
    done
env:
  - GEOMSTATS_BACKEND=numpy
